spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:file:/tmp/stelladb
    username: root
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

logging:
  level:
    org.springframework.retry: INFO

server:
  port: 9090